equinor/EchoCore

src/__tests__/plants/globalPlantsDataActions.test.ts, src/__tests__/plants/persistPlantsData.test.ts, src/plants/globalPlantsDataActions.ts, src/plants/persistPlantsData.ts, src/plants/usePlants.ts, src/state/defaultStates.ts, src/state/globalState.ts, src/state/useGlobalState.ts, src/types/plants.ts, src/types/state.ts
Added functions for getting and setting plants data in global state and local storage.
Also added useGlobalState hook.
=> Feature #36600: Added functions for getting and setting plants data

package.json, src/types/eventHub.ts
Changed name of event from 'ChangePlant' to 'PlantChanged', making it past tense
=> Change event name

.github/pull_request_template.md, package-lock.json, package.json, src/services/baseClient/baseClient.ts
-   [x] Pull request title = BugFix or Feature #UserStoryNumber: One sentence explaining **to the user** what's new/fixed.
-   [ ] Breaking change …
=> Feature #36918: get token for worker fetch 

package.json
-   [x] Pull request title = BugFix or Feature #UserStoryNumber: One sentence explaining **to the user** what's new/fixed.
-   [ ] Breaking change …
=> doc: v0.1.25

src/types/plants.ts
-   [x] Pull request title = BugFix or Feature #UserStoryNumber: One sentence explaining **to the user** what's new/fixed.
-   [ ] Breaking change …
=> Feature #37127 Add boolean hasTr2000 to Plant

.github/workflows/npm-publish.yml, packages/echo-core/package.json
=> chore: Bump version and fix publish action

.github/workflows/npm-publish.yml, packages/echo-core/package.json
=> chore: publish action

.github/workflows/npm-publish.yml, packages/echo-core/package.json
=> chore: change version

.gitignore, packages/echo-core/package.json
=> docs: bum version to 0.2.0

packages/echo-core/package-lock.json, packages/echo-core/package.json
Updated to echo-core v0.2.1, published from current main branch
=> docs: bum version to 0.2.1

package-lock.json, packages/echo-base/package-lock.json, packages/echo-base/package.json, packages/echo-base/src/__tests__/errors/BaseError.test.ts, packages/echo-base/src/__tests__/errors/NetworkError.test.ts, packages/echo-base/src/__tests__/errors/errorHandlers.test.ts, packages/echo-base/src/errors/ArgumentError.ts, packages/echo-base/src/errors/BaseError.ts, packages/echo-base/src/errors/NetworkError.ts, packages/echo-base/src/errors/errorHandlers.ts, packages/echo-base/src/errors/network/BackendError.ts, packages/echo-base/src/errors/network/ForbiddenError.ts, packages/echo-base/src/errors/network/NotFoundError.ts, packages/echo-base/src/errors/network/ValidationError.ts, packages/echo-base/src/errors/network/index.ts, packages/echo-base/src/index.ts, packages/echo-base/src/module/fetchModules.ts, packages/echo-core/package.json, packages/echo-core/src/types/state.ts
=> fix: baseError - instanceOf ForbiddenError fixed

packages/echo-core/package-lock.json, packages/echo-core/package.json
=> build: bumped versjon and publish

packages/echo-base/package-lock.json, packages/echo-base/package.json, packages/echo-base/src/index.ts, packages/echo-base/src/types/event.ts
=> feat(#39955): Bumped version of Echo-Base

packages/echo-base/package.json, packages/echo-base/src/__tests__/errors/errorHandlers.test.ts, packages/echo-base/src/errors/BaseError.ts, packages/echo-base/src/errors/NetworkError.ts, packages/echo-base/src/errors/errorHandlers.ts, packages/echo-core/package.json
Fixed Error initializer, and added UnauthorizedError BadRequestError.
Added documentation, to easier understand how to use it from the outside.
Tested with unit tests.
Bumped version of core and base to "version": "0.2.97",
=> fix: Errors &Add UnauthorizedError BadRequestError

packages/echo-core/package.json, packages/echo-core/src/services/baseClient/baseClient.ts
-   [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- …
=> fix(#42583): Upload to STID Media

packages/echo-core/package.json
=> fix: update echo-base version

.github/workflows/docs-publish.yml, .gitignore, package.json, packages/echo-base/index.ts, packages/echo-core/index.ts, packages/echo-core/src/configuration/environment.ts, tsconfig.json, typedoc.json
=> docs: auto generated docs

packages/echo-core/src/__tests__/procosysProjects/globalProcosysProjectsDataActions.test.ts, packages/echo-core/src/__tests__/procosysProjects/persistProcosysProjectsData.test.ts, packages/echo-core/src/__tests__/settings/procosysProjectSettingActions.test.ts, packages/echo-core/src/index.ts, packages/echo-core/src/procosysProjects/globalProjectsDataActions.ts, packages/echo-core/src/procosysProjects/index.ts, packages/echo-core/src/procosysProjects/persistProjectsData.ts, packages/echo-core/src/procosysProjects/useProcosysProjects.ts, packages/echo-core/src/settings/index.ts, packages/echo-core/src/settings/procosysProjectSettingsActions.ts, packages/echo-core/src/settings/useSetting.ts, packages/echo-core/src/state/defaultStates.ts, packages/echo-core/src/types/index.ts, packages/echo-core/src/types/procosysProjects.ts, packages/echo-core/src/types/settings.ts, packages/echo-core/src/types/state.ts
=> feat(#43369): Add procosys project functionality

packages/echo-base/package.json, packages/echo-core/package.json
=> chore: Bump versions

.github/workflows/npm-build.yml, .github/workflows/npm-publish-beta.yml, .github/workflows/npm-publish.yml, packages/echo-base/package-lock.json, packages/echo-base/package.json, packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-setup/package-lock.json, packages/echo-setup/package.json
=> chore: Remove npm 7 from github actions and change versions

packages/echo-base/package-lock.json, packages/echo-base/package.json, packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-setup/package-lock.json
=> chore: Remove hat from echo-base

.github/workflows/docs-publish.yml, .github/workflows/npm-publish.yml, packages/echo-base/package-lock.json, packages/echo-base/package.json, packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-setup/package-lock.json
=> chore: Change to lerna-install

.github/workflows/npm-publish.yml, packages/echo-base/package-lock.json, packages/echo-base/package.json, packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-setup/package-lock.json
=> chore: Move install before version bump

packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-core/src/types/api.ts, packages/echo-core/src/types/panel.ts, packages/echo-core/src/types/registry.ts, packages/echo-core/src/types/ui.ts
-   [x] I have updated the documentation accordingly
- …
=> refactor: routes update

packages/echo-core/package.json, packages/echo-core/src/state/defaultStates.ts, packages/echo-core/src/types/settings.ts
=> feat: add measuring points menu settings

packages/echo-base/package.json, packages/echo-base/src/types/event.ts, packages/echo-core/package.json
-   [ ] I have added tests to cover my changes
Added event for changing procosys projects.
=> feat: Add procosysProjectChanged event

packages/echo-base/package.json, packages/echo-core/package.json
=> feat: Bump versions

packages/echo-base/package-lock.json, packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-core/src/__tests__/procosysProjects/globalProcosysProjectsDataActions.test.ts, packages/echo-core/src/__tests__/settings/procosysProjectSettingActions.test.ts, packages/echo-core/src/procosysProjects/globalProjectsDataActions.ts, packages/echo-core/src/procosysProjects/useProcosysProjects.ts, packages/echo-core/src/settings/procosysProjectSettingsActions.ts, packages/echo-core/src/settings/useSetting.ts, packages/echo-core/src/state/defaultStates.ts, packages/echo-core/src/types/procosysProjects.ts, packages/echo-core/src/types/settings.ts
Removed properties from the procosys project object, leaving only the project code.
=> refactor: Remove extra properties from procosys projects

packages/echo-core/src/state/defaultStates.ts, packages/echo-core/src/types/settings.ts
After discussions these settings are handled in echopedia …
=> feat: remove unused settings

packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-core/src/hooks/index.ts, packages/echo-core/src/hooks/usePanelUI.ts, packages/echo-core/src/hooks/usePanels.ts, packages/echo-core/src/types/panel.ts, packages/echo-core/src/types/state.ts
Added back some logic for the panel UI
=> fix: Add panel UI back

packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-core/src/index.ts, packages/echo-core/src/services/analytics/analyticsTelemetryFilter.test.ts, packages/echo-core/src/services/analytics/analyticsTelemetryFilter.ts, packages/echo-core/src/services/analytics/analyticsTypes.ts, packages/echo-core/src/services/analytics/index.ts
Example on how to use it to exclude echo3d page views:
```
analyticsConfiguration.addTelemetryNameFilter({
shouldExclude: (name: string, telemetryItem: ITelemetryItem) => {
const isEchoSearch = name === 'Echo | Search';
const uri: string = ((telemetryItem?.baseData ?? {})['uri'] as string) ?? '';
const shouldExcludeItemFromAnalytics = isEchoSearch && uri.includes('/echo3d');
return shouldExcludeItemFromAnalytics;
}
});
```
What types …
=> feat: 51610 analytics exclude filter: add telemetryItem

README.md
Updated README with info on how to release echo-core and echo-base.
This should be updated when we get our release through GitHub actions to work.
=> chore: Update README with release steps

packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-core/src/EchoCore.ts, packages/echo-core/src/__tests__/services/hookRegistry.test.ts, packages/echo-core/src/services/hookRegistry/hookRegistry.ts
-   [x] Breaking change (fix or feature that would cause existing functionality to change)
- …
=> feat: #53426 - Add more hooks to hook registry

jest.config.js, package-lock.json, package.json, packages/echo-core/package-lock.json, packages/echo-core/package.json
Updated npm packages. 
[Optionally place any follow-up comments, remarks, observations, or notes here for future reference]
=> feat: Update package versions

packages/echo-core/package-lock.json, packages/echo-core/package.json
=> feat: Bumping version: using base v0.4.0

package-lock.json, packages/echo-base/package.json, packages/echo-base/src/utils/jsonParseUtils.ts, packages/echo-base/src/utils/storage.ts, packages/echo-core/package-lock.json, packages/echo-core/package.json
Adding the date parser to echo-base since we are using JSON.parse here. Copied it from EchoUtils, since we don't want to have EchoUtils as a dependency in base.
=> feat: Add date parser to echo-base

packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-core/src/types/components.ts, packages/echo-core/src/types/index.ts
Record<string, unknown> didn't work for the RouteComponentProps, so added StaticContext instead.
=> fix: Add StaticContext to RouteComponentProps

jest.config.js, packages/echo-core/setupTests.js, packages/echo-core/src/__tests__/services/graphUtils.test.ts, packages/echo-core/src/services/analytics/appInsightWrapper.test.ts, packages/echo-core/src/services/baseClient/fetchWithTokenLogic.test.ts
-   [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- …
=> test: fix jest infrastructure

packages/echo-core/package.json, packages/echo-core/src/configuration/environment.ts
=> feat: Added echo 3d web enabled to environment variables

packages/echo-base/README.md, packages/echo-core/README.md
Just updated the readme with breaking changes. No new release needed, as it's only the readme that has changed.
=> chore: updated base readme with breaking changes

packages/echo-base/package-lock.json, packages/echo-base/package.json, packages/echo-base/src/types/module.ts
Added fileUris for dev, qa and test to the ModuleMetaData interface, since we use it in EchopediaWeb.
=> feat: Add fileUri for different envs in type

packages/echo-core/package-lock.json, packages/echo-core/package.json
Bumping echo-base version in echo-core.
=> chore: Bump base version

packages/echo-core/src/configuration/environment.ts
- Added `REACT_APP_ECHOMAP_WEB_URL`&  `REACT_APP_ECHOMAP_WEB_ENABLED` to env to further implement feature toggle
=> feat: 96873 EchoMaps feature toggle env vars

packages/echo-core/package-lock.json, packages/echo-core/package.json, packages/echo-core/src/types/echoEvents.ts
-   [ ] I have added tests to cover my changes
As part of adding the new fullscreen floating button/chip, we need a new event hub event name.
Adding it in this PR.
For more details check: https://github.com/equinor/EchopediaWeb/pull/1862
* EchoFramework: https://github.com/equinor/EchoFramework/pull/581
* EchopediaWeb: …
=> feat: #112109 - Hide top and sidebars with floating buttons
