.gitignore
packages/echo-core/src/hooks/useAuthenticate.ts

-   [x] All new and existing tests passed - no tests written for this initially 
-   [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id) 
- found in relation to #36288: Make a pilot for including Ayelix 360 pictures in EchoInfield 
-   [ ] …

fix: #36288: useAuthenticate returns false if authprovider is initially authenticated

---

packages/echo-base/package.json
packages/echo-base/src/errors/BaseError.ts
packages/echo-core/package.json

insatanceOf was not working, fixed by
https://stackoverflow.com/questions/55065742/implementing-instanceof-checks-for-custom-typescript-error-instances

fix: instanceOf BaseError and child classes now works

---

packages/echo-core/package-lock.json
packages/echo-core/src/EchoCore.ts
packages/echo-core/src/__tests__/services/authProvider.test.ts
packages/echo-core/src/__tests__/services/errorHandler.test.ts
packages/echo-core/src/__tests__/services/graphUtils.test.ts
packages/echo-core/src/services/errorHandler/errorHandler.ts
packages/echo-core/src/utils/module.ts

-   [x] I have added tests to cover my changes
Added possibility to set and call an errorHandler function on EchoCore: on the long run the goal would be to be able to decouple ayelix completely from echopediaWeb.
With this change `echopediaWeb` will be responsible to call `EchoCore.setErrorHandler()` function on Echo app initialization, so it can be called by …

feat: #49136 In goal of moving ayelix dependencies: added errorHandler registration

---

packages/echo-base/package-lock.json
packages/echo-base/src/module/create.ts
packages/echo-base/src/module/loader.ts
packages/echo-base/src/module/strategies.ts
packages/echo-core/package-lock.json
packages/echo-core/package.json

We only want to start the process of loading a module when we are on that module's path. This is a suggestion of how we can achieve that. The mediator from Core (which calls the `startLoadingModules` function) will provide the current path. Which we use here to decide if we want to load the module or not.
This is only a suggestion, and maybe a step in the right direction. We might want to look more into unloading modules as well, but this could be more of an MVP.
You need both this branch, and the [related branch](https://github.com/equinor/EchoFramework/pull/79) in EchoFramework for this to work.
In echo-base do:
```
npm run build
yalc publish
```
In echo-framework do:
```
yalc add @equinor/echo-base
npm install
npm run build
yalc publish
```
In EchopediaWeb do:
```
yalc add …
```

feat: Load module when on its path

---

packages/echo-core/package-lock.json
packages/echo-core/package.json
packages/echo-core/rollup.config.js
packages/echo-core/src/hooks/useInternalLink.ts

We don't need react-router as a peer dependency in echo-core. This was also causing some issues when building EchopediaWeb, complaining that we don't have it installed as a dependency there.
Removing it, and replacing it with react-router-dom.

refactor: Replace react router with react router dom

---

packages/echo-base/package-lock.json
packages/echo-base/package.json
packages/echo-base/src/module/create.ts
packages/echo-base/src/module/loader.ts
packages/echo-base/src/module/strategies.ts

-   [x] Breaking change (fix or feature that would cause existing functionality to change)
- …

feat!: #55685 Revert load on path changes

---

README.md
packages/echo-base/README.md
packages/echo-base/package-lock.json
packages/echo-base/package.json
packages/echo-base/src/__tests__/errors/NetworkError.test.ts
packages/echo-base/src/__tests__/errors/errorHandlers.test.ts
packages/echo-base/src/__tests__/module/strategies.test.ts
packages/echo-base/src/errors/ArgumentError.ts
packages/echo-base/src/errors/BaseError.test.ts
packages/echo-base/src/errors/BaseError.ts
packages/echo-base/src/errors/NetworkError.ts
packages/echo-base/src/errors/toError.ts
packages/echo-base/src/module/errors.ts
packages/echo-base/src/module/load.ts
packages/echo-base/src/module/strategies.ts
packages/echo-base/src/types/error.ts
packages/echo-base/src/types/loader.ts

- BaseError now preserve the innerException name, message and stack trace, in addition to any other properties.
- BaseError now takes a name as required argument, to avoid minifying it to a single letter in appInsights.
Breaking change:
Classes that extends BaseError are now required to specify the name. It used to get the subClass name automatically, but this is not working in production because of code obfuscation/minify. 
Tested with unit tests.

fix!: BaseError innerException name/message

---

packages/echo-core/package.json
packages/echo-core/src/services/analytics/analyticsModule.ts

The functions for tracking offline and online activity were not properly called when added to the event listener.
Tested by observing that the `setOffline` and `setOnline` are being called now, as opposed to before.
You can yalc this branch to EchopediaWeb, go offline, click around the app for a bit, go online again, and observe in the console that your activity has been logged upon going online again.

fix(#57347): Offline and online not logged to app insights

---

packages/echo-core/package.json
packages/echo-core/src/__tests__/actions/legendOptionsStateActions.test.ts
packages/echo-core/src/actions/index.ts
packages/echo-core/src/state/defaultStates.ts
packages/echo-core/src/types/legend.ts

To make legend items togglable I added `toggledStatuses` to the LegendOptions

feat: Add toggledStatuses to LegendOptions

---

.gitignore
packages/echo-core/package-lock.json
packages/echo-core/package.json
packages/echo-core/src/services/hookRegistry/hookRegistry.ts

feat: add commPack and mcPack hooks in the registry

---

packages/echo-core/package-lock.json
packages/echo-core/package.json
packages/echo-core/src/services/hookRegistry/hookRegistry.ts

-   [ ] I have added tests to cover my changes
Deprecating RegisteredHookName enum, and setting a string type. The RegisteredHookName is moved to Framework as a duplicate, and it will be removed from Core in a future update. This is done to avoid breaking changes. 
Version number will be increase accordingly.

refactor: deprecate RegisteredHookName enum

---

packages/echo-core/package-lock.json
packages/echo-core/package.json

-   [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- …

fix: Aligning core peer and dev deps

---

packages/echo-base/package-lock.json
packages/echo-base/package.json
packages/echo-base/src/__tests__/utils/storage.test.ts
packages/echo-base/src/utils/storage.ts

We were checking if data was a string before stringifying it when setting it in localstorage. We should stringify the data, even if it is a string to ensure correct types when parsing it. 
Removed this check, and we are now stringifying everything before adding it to localstorage.

fix: Stringify all localstorage data

---

packages/echo-base/package-lock.json
packages/echo-base/package.json
packages/echo-base/src/module/dependency.ts
packages/echo-base/src/module/load.ts

When loading the modules, we were using `Promise.all` to resolve the module promises. This meant that if one module was rejected due to an error, all of them would be rejected. 
To properly handle rejected modules, we switch to using `Promise.allSettled` so we can filter out the resolved modules.
A module might be rejected due to, e.g., a fileUri which is not approved by our CORS policy. This is a safe guard so the rejected module does not reject the rest of the app. The rejected module will still show up as a blank page, but the other modules will not be affected.
The test branch should be running with this version of base. The camera module will be blank, and there will be an error in the console saying that the module could not load. The rest of the app should work fine.

fix(#65850): Handle rejected echo modules

---

packages/echo-core/package-lock.json
packages/echo-core/package.json
packages/echo-core/src/services/authentication/authProviderConfig.ts

When adding new SWAs in Azure, we need to request admin consent the first time the app is opened. Usually this request should include all the API permissions we have added to the app. In our case, it only included Microsoft Graph in the request, and not the echopedia APIs.
Changing the request scope to `.default` includes the proper API permissions in the request, meaning we don't have to email equinor azure admins to manually grant consent anymore. 
After the change you can see the Echopedia APIs are included in the request (this is from the XLD app):

fix(#73946): Change login request scope to .default

---

packages/echo-base/package-lock.json
packages/echo-base/package.json
packages/echo-base/src/__tests__/errors/NetworkError.test.ts
packages/echo-base/src/errors/BaseError.test.ts
packages/echo-base/src/errors/BaseError.ts
packages/echo-base/src/errors/errorUtils.test.ts
packages/echo-base/src/errors/errorUtils.ts

Please also review this commit which I managed to push to the main branch:
https://github.com/equinor/EchoCore/commit/687c63e9af6432afc482f340e590438463181382
We didn't return the value if it was set to false or empty string.
Added errorUtils helper function for checking if it's an error, baseError, etc. Since error instanceof NetworkError doesn't work across modules as described here: https://medium.com/@samjwright/why-is-instanceof-my-object-returning-false-in-typescript-fec74df5c2a8
Tested with unit tests

fix: 69299 Added ErrorUtils.is.error etc

---

packages/echo-base/package-lock.json
packages/echo-base/package.json
packages/echo-base/src/errors/BaseError.ts
packages/echo-base/src/errors/index.ts
packages/echo-core/CHANGELOG.md
packages/echo-core/package-lock.json
packages/echo-core/package.json
packages/echo-core/src/services/analytics/errorToExceptionTelemetry.ts

Had forgotten to export echoUtils.
Fixed: findPropertyByName now supports object, not just Error & Record.
Also updated changelog for the past versions

fix: 69299 Release v0.6.10, Export errorUtils & updated changelog

---

packages/echo-core/CHANGELOG.md
packages/echo-core/package-lock.json
packages/echo-core/package.json
packages/echo-core/src/__tests__/plants/globalPlantsDataActions.test.ts
packages/echo-core/src/__tests__/services/authProvider.test.ts
packages/echo-core/src/__tests__/services/graphUtils.test.ts
packages/echo-core/src/actions/plantsData.ts
packages/echo-core/src/services/authentication/authProvider.ts
packages/echo-core/src/services/baseClient/authenticationError.ts
packages/echo-core/src/services/baseClient/baseClient.ts
packages/echo-core/src/services/graph/graphUtils.ts
packages/echo-core/src/types/userProperties.ts

Temporary published as 0.7.0-rc1, and used in dev for testing. Also tested with yalc.
The stuck api calls happens after 1-2 hours of idle iPad. And sometimes on PC. We now auto refresh it in echoClient.getAccessToken 
-   EchoAuthProvider.userProperties is now correctly defined as optional. Instead use getUserProperties or getUserAccount to automatically start auth process if needed.
-   EchoAuthProvider.userProperties.loginError removed. The auth process will now instead throw error if auth fails, forcing the app to deal with the error (log it to appInsight).
-   echoClient.getAccessToken will authenticate if necessary.
-   getPlantsData will now load data from localStorage if it hasn't been set/loaded yet

fix: #84416 Stuck api call because of outdated token.

---

packages/echo-core/package-lock.json
packages/echo-core/package.json

- Bumped version to release changes in envVars done here (https://github.com/equinor/EchoCore/commit/30f7dd2e980e080e05d3c1b543d8983b12a26335)

chore: Version bump to 0.7.4

---

packages/echo-core/package-lock.json
packages/echo-core/package.json
packages/echo-core/src/types/echoEvents.ts

When clicking Data Selection button in turnaround Grid, the left side bucket panel should display with the turnaround menu open. 
This PR adds an event which is emitted when clicking the Data Selection button.
EchopediaWeb: https://github.com/equinor/EchopediaWeb/pull/1863
https://dev.azure.com/EquinorASA/Echo/_workitems/edit/121829

feat: #120905 - Event to show turnaround menu in bucket panel
